---
name: Check

on:
  workflow_call:
    inputs:
      projectDir:
        description: "project to be checked (path to project directory)"
        type: string
        required: false
        default: '.'

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Check with Gradle
        run: ./gradlew -p ${{ inputs.projectDir }} clean check

      - name: Generate Coverage report
        if: ${{ inputs.projectDir == '.' }}
        run: ./gradlew -p ${{ inputs.projectDir }} koverXmlReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ inputs.projectDir == '.' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
