---
name: Java Example check

# This workflow is now integrated into required-status-checks.yml
# Keeping it for manual triggers only
on:
  workflow_dispatch:

jobs:
  call-check:
    uses: ./.github/workflows/check.yml
    with:
      projectDir: 'examples/java'
    secrets: inherit
