---
name: Loxone Client Kotlin check

# This workflow is now replaced by gradle-check-required.yml
# Keeping it for manual triggers only
on:
  workflow_dispatch:

jobs:
  call-check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
