---
name: Loxone Client Kotlin check

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/*.versions.toml'
      - '*.gradle.*'
      - 'src/**'

jobs:
  call-check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
